<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXUjYtLB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXUjYtLB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXUjYtLB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXUjYtLB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXUjYtLB\App_KernelDevDebugContainer([
    'container.build_hash' => 'XUjYtLB',
    'container.build_id' => '74b82025',
    'container.build_time' => 1705500262,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXUjYtLB');
